import { describe, it, expect } from 'vitest';
import { detectAndParse } from './detect.js';

describe('detectAndParse', () => {
  it('should auto-detect npm lockfile', () => {
    const content = JSON.stringify({
      lockfileVersion: 3,
      packages: { '': { name: 'test', version: '1.0.0' }, 'node_modules/foo': { version: '1.0.0' } },
    });
    expect(detectAndParse(content)?.type).toBe('npm');
  });
  it('should auto-detect yarn lockfile', () => {
    const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nfoo@^1.0.0:\n  version "1.0.0"\n`;
    expect(detectAndParse(content)?.type).toBe('yarn');
  });
  it('should auto-detect pnpm lockfile', () => {
    const content = `lockfileVersion: '9.0'\n\npackages:\n  foo@1.0.0:\n    resolution: {integrity: sha512-xxx}\n`;
    expect(detectAndParse(content)?.type).toBe('pnpm');
  });
  it('should return null for unknown format', () => {
    expect(detectAndParse('random text')).toBeNull();
  });
});
