import { describe, it, expect } from 'vitest';
import { YarnParser } from './yarn-parser.js';

const YARN_CLASSIC_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

axios@^1.7.0:
  version "1.7.2"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.7.2.tgz#abc123"
  integrity sha512-xxx
  dependencies:
    follow-redirects "^1.15.6"

follow-redirects@^1.15.6:
  version "1.15.6"
  resolved "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.15.6.tgz#def456"
  integrity sha512-yyy
`;

const YARN_SCOPED_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@types/node@^22.0.0":
  version "22.5.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-22.5.0.tgz#abc"
  integrity sha512-zzz
`;

describe('YarnParser', () => {
  const parser = new YarnParser();

  describe('canParse', () => {
    it('должен распознать yarn.lock v1', () => {
      expect(parser.canParse(YARN_CLASSIC_LOCKFILE)).toBe(true);
    });
    it('должен отклонить package-lock.json', () => {
      expect(parser.canParse(JSON.stringify({ lockfileVersion: 3 }))).toBe(false);
    });
  });

  describe('parse', () => {
    it('должен извлечь пакеты из yarn.lock classic', () => {
      const result = parser.parse(YARN_CLASSIC_LOCKFILE);
      expect(result.type).toBe('yarn');
      expect(result.packages).toHaveLength(2);
      const axios = result.packages.find((p) => p.name === 'axios');
      expect(axios).toBeDefined();
      expect(axios!.version).toBe('1.7.2');
      expect(axios!.dependencies).toEqual({ 'follow-redirects': '^1.15.6' });
    });
    it('должен обработать scoped-пакеты', () => {
      const result = parser.parse(YARN_SCOPED_LOCKFILE);
      expect(result.packages).toHaveLength(1);
      expect(result.packages[0].name).toBe('@types/node');
      expect(result.packages[0].version).toBe('22.5.0');
    });
  });
});
