import { describe, it, expect } from 'vitest';
import { isOk, isErr } from '../../fp/result.js';
import { detectAndParseFp } from '../../parsers/detect-fp.js';

describe('detectAndParseFp', () => {
  it('should auto-detect npm lockfile', () => {
    const content = JSON.stringify({
      lockfileVersion: 3,
      packages: { '': { name: 'test', version: '1.0.0' }, 'node_modules/foo': { version: '1.0.0' } },
    });
    const result = detectAndParseFp(content);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) expect(result.value.type).toBe('npm');
  });

  it('should auto-detect yarn lockfile', () => {
    const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nfoo@^1.0.0:\n  version "1.0.0"\n`;
    const result = detectAndParseFp(content);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) expect(result.value.type).toBe('yarn');
  });

  it('should auto-detect pnpm lockfile', () => {
    const content = `lockfileVersion: '9.0'\n\npackages:\n  foo@1.0.0:\n    resolution: {integrity: sha512-xxx}\n`;
    const result = detectAndParseFp(content);
    expect(isOk(result)).toBe(true);
    if (isOk(result)) expect(result.value.type).toBe('pnpm');
  });

  it('should return Err for unknown format', () => {
    const result = detectAndParseFp('random text');
    expect(isErr(result)).toBe(true);
  });
});
