import { describe, it, expect } from 'vitest';
import { isOk, isErr } from '../../fp/result.js';
import { yarnParser } from '../../parsers/yarn.js';

const YARN_CLASSIC_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

axios@^1.7.0:
  version "1.7.2"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.7.2.tgz#abc123"
  integrity sha512-xxx
  dependencies:
    follow-redirects "^1.15.6"

follow-redirects@^1.15.6:
  version "1.15.6"
  resolved "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.15.6.tgz#def456"
  integrity sha512-yyy
`;

const YARN_SCOPED_LOCKFILE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@types/node@^22.0.0":
  version "22.5.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-22.5.0.tgz#abc"
  integrity sha512-zzz
`;

describe('yarnParser', () => {
  describe('canParse', () => {
    it('should recognize yarn.lock v1', () => {
      expect(yarnParser.canParse(YARN_CLASSIC_LOCKFILE)).toBe(true);
    });
    it('should reject package-lock.json', () => {
      expect(yarnParser.canParse(JSON.stringify({ lockfileVersion: 3 }))).toBe(false);
    });
  });

  describe('parse', () => {
    it('should extract packages from yarn.lock classic', () => {
      const result = yarnParser.parse(YARN_CLASSIC_LOCKFILE);
      expect(isOk(result)).toBe(true);
      if (!isOk(result)) return;
      expect(result.value.type).toBe('yarn');
      expect(result.value.packages).toHaveLength(2);
      const axios = result.value.packages.find((p) => p.name === 'axios');
      expect(axios).toBeDefined();
      expect(axios!.version).toBe('1.7.2');
      expect(axios!.dependencies).toEqual({ 'follow-redirects': '^1.15.6' });
    });

    it('should handle scoped packages', () => {
      const result = yarnParser.parse(YARN_SCOPED_LOCKFILE);
      expect(isOk(result)).toBe(true);
      if (!isOk(result)) return;
      expect(result.value.packages).toHaveLength(1);
      expect(result.value.packages[0].name).toBe('@types/node');
      expect(result.value.packages[0].version).toBe('22.5.0');
    });

    it('should return Err for oversized content', () => {
      const oversized = '# yarn lockfile v1\n' + 'a'.repeat(50 * 1024 * 1024 + 1);
      const result = yarnParser.parse(oversized);
      expect(isErr(result)).toBe(true);
    });
  });
});
